version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www
permissions:
  - object: /var/www
    pattern: '**'
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
