version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www
permissions:
  - object: /var/www
    pattern: '**'
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/check_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/reload_nginx.sh
      timeout: 300
      runas: root
